// *********************************************************
   This file is autogenerated DO NOT EDIT this file
// *********************************************************

static const uint8_t _coderTypeArr[96] = {
<DEFAULT>,	MSGC_U16,	MSGC_U16,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 0..7 */,
<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 8..15 */,
<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	MSGC_U16,	MSGC_U16,	MSGC_U16,	<DEFAULT>,	MSGC_U16,	 /* 16..23 */,
<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	 /* 24..31 */,
MSGC_U16,	MSGC_U16,	MSGC_U16,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 32..39 */,
<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 40..47 */,
<DEFAULT>,	MSGC_U16,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 48..55 */,
<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 56..63 */,
<DEFAULT>,	MSGC_U16,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	 /* 64..71 */,
<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	MSGC_U16,	 /* 72..79 */,
MSGC_U16,	MSGC_U16,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	<DEFAULT>,	MSGC_U16,	 /* 80..87 */,
MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_NONE,	MSGC_U16,	MSGC_U16,	MSGC_U16U16,	 /* 88..95 */,
};


/*********************************************************************/

static const coder_fptr_t _coderTypeFptrArr[MSGC_TYPE_MAX] = {
    &MsgcCoderU16,
    &MsgcCoderU16U16,
    &MsgcCoderU16U16U16,
    &MsgcCoderU32,
    &MsgcCoderU32U32U16U8U8,
};


/*********************************************************************/

static const decoder_fptr_t _decoderTypeFptrArr[MSGC_TYPE_MAX] = {
    &MsgcDecoderU16,
    &MsgcDecoderU16U16,
    &MsgcDecoderU16U16U16,
    &MsgcDecoderU32,
    &MsgcDecoderU32U32U16U8U8,
};
END OF FILE
