// *********************************************************
   This file is autogenerated DO NOT EDIT this file
// *********************************************************

typedef enum {
    MSGC_U16,
    MU16,
    MSGC_U16U16,
    MU16U16,
    MSGC_U16U16U16,
    MU16U16U16,
    MSGC_U32,
    MU32,
    MSGC_U32U32U16U8U8,
    MU32U32U16U8U8,
    MSGC_TYPE_MAX
} msgc_type_t;


/*********************************************************************/

static inline void APP_MSGC_comp_TMR_SIGNAL_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_TMR_SIGNAL_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_TIME_TICK_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_TIME_TICK_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_BELT_STATUS_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_BELT_STATUS_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_BATT_STATUS_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_BATT_STATUS_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_CHARGE_CURRENT_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_CHARGE_CURRENT_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_SWITCH_EVENT_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_SWITCH_EVENT_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_SET_DATA_MODE_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_SET_DATA_MODE_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_GET_DATA_MODE_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_GET_DATA_MODE_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_FULL_CLK_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_FULL_CLK_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_REFERENCE_CLK_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_REFERENCE_CLK_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_GET_SERNUM_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_GET_SERNUM_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_GET_FW_REV_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_GET_FW_REV_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_CTRL_STATE_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_CTRL_STATE_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_UIND_CMD_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_UIND_CMD_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_CHARGER_CONNECT_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_CHARGER_CONNECT_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_PWR_STATE_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_PWR_STATE_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_BATT_LEVEL_FORCED_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_BATT_LEVEL_FORCED_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_CTRL_STATE_FORCED_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_CTRL_STATE_FORCED_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_CTRL_STATE_REQ_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_CTRL_STATE_REQ_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_DEBUG_SET_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_DEBUG_SET_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_SET_IMM_ALERT_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_SET_IMM_ALERT_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_GET_CH_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_GET_CH_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_SENDER_TEST_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_SENDER_TEST_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_RESET_TEST_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_RESET_TEST_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_PING1_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_PING1_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_PONG1_U16( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, p0);
}

static inline void APP_MSGC_decomp_PONG1_U16( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}



/*********************************************************************/

static inline void APP_MSGC_comp_PONG2_U16U16( msgc_t *mc_ptr, const uint16_t p0, const uint16_t p1 ) {
APP_MSGC_comp_U16U16( mc_ptr, p0, p1);
}

static inline void APP_MSGC_decomp_PONG2_U16U16( msgc_t *mc_ptr, uint16_t *p0, uint16_t *p1 ) {
APP_MSGC_decomp_U16U16( mc_ptr, p0, p1);
}



/*********************************************************************/

END OF FILE
