// *********************************************************
   This file is autogenerated DO NOT EDIT this file
// *********************************************************

typedef enum {
    MSGID_TMR_SIGNAL,	= 0x01,	 /**< Time signal                                  */
    MSGID_TIME_TICK,	= 0x02,	 /**< Time tick from OS                            */
    MSGID_BELT_STATUS,	= 0x13,	 /**< Chest belt status change                     */
    MSGID_BATT_STATUS,	= 0x14,	 /**< Battery status change                        */
    MSGID_CHARGE_CURRENT,	= 0x15,	 /**< Charge current (in mA)                       */
    MSGID_SWITCH_EVENT,	= 0x17,	 /**< Push-button (on/off switch) status change    */
    MSGID_SET_DATA_MODE,	= 0x1b,	 /**< Set Data logging mode                        */
    MSGID_GET_DATA_MODE,	= 0x1c,	 /**< Get Data logging mode                        */
    MSGID_FULL_CLK,	= 0x1d,	 /**< Get full clock time                          */
    MSGID_REFERENCE_CLK,	= 0x1e,	 /**< Get reference clock time                     */
    MSGID_GET_SERNUM,	= 0x1f,	 /**< Get CU serial number                         */
    MSGID_GET_FW_REV,	= 0x20,	 /**< Get CU firmware revision                     */
    MSGID_CTRL_STATE,	= 0x21,	 /**< Control status change                        */
    MSGID_UIND_CMD,	= 0x22,	 /**< User Indicator (LED or vibrator) act. cmd    */
    MSGID_CHARGER_CONNECT,	= 0x31,	 /**< Charger connected or disconnected            */
    MSGID_PWR_STATE,	= 0x41,	 /**< Set or rep power state for uC and peripherals*/
    MSGID_BATT_LEVEL_FORCED,	= 0x4f,	 /**< Battery level forced - added by steffend 20120809    */
    MSGID_CTRL_STATE_FORCED,	= 0x50,	 /**< Control status forced - added by steffend 20120809   */
    MSGID_CTRL_STATE_REQ,	= 0x51,	 /**< Control status request - added by steffend 20120809   */
    MSGID_DEBUG_SET,	= 0x57,	 /**< Control Debug                  */
    MSGID_SET_IMM_ALERT,	= 0x58,	 /**< Set immidiate alert - added by steffend 20130321  */
    MSGID_GET_CH,	= 0x59,	 /**< Character from console in PC-app */
    MSGID_SENDER_TEST,	= 0x5a,	 /**< Test output from task_sender_class */
    MSGID_RESET_TEST,	= 0x5b,	 /**< Generic reset to processes  */
    MSGID_PING0,	= 0x5c,	 /**< ThingMl test message  */
    MSGID_PING1,	= 0x5d,	 /**< ThingMl test message  */
    MSGID_PONG1,	= 0x5e,	 /**< ThingMl test message  */
    MSGID_PONG2,	= 0x5f,	 /**< ThingMl test message  */
    MSGID_ID_SIZE      /**< End of ENUM ... must be place as last entry */
} msg_id_t;
END OF FILE
