
// *********************************************************
//   This file is autogenerated by RCD_scripter DO NOT EDIT this file.
// *********************************************************

#include "includes.h"
#include "app_msgc_gen.h"

const uint8_t APP_MSGC_CoderTypeArr[50] = {
MSGC_NONE,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	 /* 0..7 */
MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	 /* 8..15 */
MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	 /* 16..23 */
MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16U16,	MSGC_U16,	MSGC_NONE,	MSGC_U16,	 /* 24..31 */
MSGC_U16,	MSGC_U16U16,	MSGC_U8ARR14,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	 /* 32..39 */
MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	MSGC_U16,	 /* 40..47 */
MSGC_U16,	MSGC_U16U16,	};

/*********************************************************************/

// END OF FILE
