
// *********************************************************
//   This file is autogenerated by RCD_scripter DO NOT EDIT this file.
// *********************************************************


#include "app_msg.h"


#ifndef APP_MSGC_GEN_H
#define APP_MSGC_GEN_H    

typedef enum {
    MSGC_NONE,
    MSGC_U16,
    MSGC_U16U16,
    MSGC_U8ARR14,
    MSGC_TYPE_MAX
} msgc_type_t;

/*********************************************************************/


typedef struct {
    uint8_t Dummy; // No params
} msgc_param_none_t;


typedef struct {
    uint16_t U161;
} msgc_param_u16_t;


typedef struct {
    uint16_t U161;
    uint16_t U162;
} msgc_param_u16u16_t;



//typedef uint8_t u8Arr14_t[14];
typedef struct {
//    u8Arr14_t Array14;
    uint8_t Array14[14];
    uint8_t   Len;
} msgc_param_u8arr14_t;


typedef union {
    msgc_param_none_t	NONE;
    msgc_param_u16_t	U16;
    msgc_param_u16u16_t	U16U16;
    msgc_param_u8arr14_t	U8ARR14;
    msg_t   MsgTypeStruct;
} msgc_param_union_t;


typedef struct {
    uint32_t   MsgId;
    uint32_t   ParamType;
    msgc_param_union_t ParamUnion;
} msgc_t;


/*********************************************************************/

extern const uint8_t APP_MSGC_CoderTypeArr[50];

/*********************************************************************/


static inline void APP_MSGC_comp_NONE (msgc_t *mc_ptr,
                                      const msg_id_t msgid)
{
    mc_ptr->MsgId  = msgid;
    mc_ptr->ParamType = MSGC_NONE;
}


static inline void APP_MSGC_decomp_NONE (msgc_t *mc_ptr)
{
    // No params to handle
}


/*********************************************************************/


static inline void APP_MSGC_comp_U16 (msgc_t *mc_ptr,
                                      const msg_id_t msgid,
                                      const uint16_t u161)
{
    mc_ptr->MsgId  = msgid;
    mc_ptr->ParamType = MSGC_U16;
    mc_ptr->ParamUnion.U16.U161 = u161;
}


static inline void APP_MSGC_decomp_U16 (msgc_t *mc_ptr,
                                        uint16_t *u161_ptr)
{
    if (mc_ptr->ParamType == MSGC_U16) {
        if (u161_ptr != NULL) {
            *u161_ptr = mc_ptr->ParamUnion.U16.U161;
        }
    }
}


/*********************************************************************/


static inline void APP_MSGC_comp_U16U16 (msgc_t *mc_ptr,
                                           const msg_id_t msgid,
                                           const uint16_t u161,
                                           const uint16_t u162)
{
    mc_ptr->MsgId  = msgid;
    mc_ptr->ParamType = MSGC_U16U16;
    mc_ptr->ParamUnion.U16U16.U161 = u161;
    mc_ptr->ParamUnion.U16U16.U162 = u162;
}


static inline void APP_MSGC_decomp_U16U16 (msgc_t *mc_ptr,
                                           uint16_t *u161_ptr,
                                           uint16_t *u162_ptr)
{
    if (mc_ptr->ParamType == MSGC_U16U16) {
        if (u161_ptr != NULL) {
            *u161_ptr = mc_ptr->ParamUnion.U16U16.U161;
        }
        if (u162_ptr != NULL) {
            *u162_ptr = mc_ptr->ParamUnion.U16U16.U162;
        }
    }
}


/*********************************************************************/


static inline void APP_MSGC_comp_U8ARR14 (msgc_t *mc_ptr,
                                      const msg_id_t msgid,
                                      const uint8_t *u8Arr_ptr,
                                      uint8_t len)
{
    if(len > 14) len = 14;
    mc_ptr->MsgId  = msgid;
    mc_ptr->ParamType = MSGC_U8ARR14;
    memcpy(mc_ptr->ParamUnion.U8ARR14.Array14, u8Arr_ptr, len);
    mc_ptr->ParamUnion.U8ARR14.Len = len;
}


static inline void APP_MSGC_decomp_U8ARR14 (msgc_t *mc_ptr,
                                      uint8_t  **u8Arr_ptr_ptr,
                                      uint8_t   *len_ptr)
{
    if (mc_ptr->ParamType == MSGC_U8ARR14) {
        if (u8Arr_ptr_ptr != NULL) {
            *u8Arr_ptr_ptr = mc_ptr->ParamUnion.U8ARR14.Array14;
        }
        if (len_ptr != NULL) {
            *len_ptr = mc_ptr->ParamUnion.U8ARR14.Len;
        }
    }
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_TMR_SIGNAL( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_TMR_SIGNAL, p0);
}

static inline void APP_MSGC_decomp_MSGID_TMR_SIGNAL( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_TIME_TICK( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_TIME_TICK, p0);
}

static inline void APP_MSGC_decomp_MSGID_TIME_TICK( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BELT_STATUS( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BELT_STATUS, p0);
}

static inline void APP_MSGC_decomp_MSGID_BELT_STATUS( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BATT_STATUS( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BATT_STATUS, p0);
}

static inline void APP_MSGC_decomp_MSGID_BATT_STATUS( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_CHARGE_CURRENT( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_CHARGE_CURRENT, p0);
}

static inline void APP_MSGC_decomp_MSGID_CHARGE_CURRENT( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_SWITCH_EVENT( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_SWITCH_EVENT, p0);
}

static inline void APP_MSGC_decomp_MSGID_SWITCH_EVENT( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_SET_DATA_MODE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_SET_DATA_MODE, p0);
}

static inline void APP_MSGC_decomp_MSGID_SET_DATA_MODE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_GET_DATA_MODE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_GET_DATA_MODE, p0);
}

static inline void APP_MSGC_decomp_MSGID_GET_DATA_MODE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_FULL_CLK( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_FULL_CLK, p0);
}

static inline void APP_MSGC_decomp_MSGID_FULL_CLK( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_REFERENCE_CLK( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_REFERENCE_CLK, p0);
}

static inline void APP_MSGC_decomp_MSGID_REFERENCE_CLK( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_GET_SERNUM( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_GET_SERNUM, p0);
}

static inline void APP_MSGC_decomp_MSGID_GET_SERNUM( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_GET_FW_REV( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_GET_FW_REV, p0);
}

static inline void APP_MSGC_decomp_MSGID_GET_FW_REV( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_CTRL_STATE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_CTRL_STATE, p0);
}

static inline void APP_MSGC_decomp_MSGID_CTRL_STATE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_UIND_CMD( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_UIND_CMD, p0);
}

static inline void APP_MSGC_decomp_MSGID_UIND_CMD( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_CONN_STATUS( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_CONN_STATUS, p0);
}

static inline void APP_MSGC_decomp_MSGID_CONN_STATUS( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_ADC_DATA( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_ADC_DATA, p0);
}

static inline void APP_MSGC_decomp_MSGID_ADC_DATA( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_GOTO_STANDBY( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_GOTO_STANDBY, p0);
}

static inline void APP_MSGC_decomp_MSGID_GOTO_STANDBY( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_UIND_OVR_CMD( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_UIND_OVR_CMD, p0);
}

static inline void APP_MSGC_decomp_MSGID_UIND_OVR_CMD( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_CHARGER_CONNECT( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_CHARGER_CONNECT, p0);
}

static inline void APP_MSGC_decomp_MSGID_CHARGER_CONNECT( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PWR_STATE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PWR_STATE, p0);
}

static inline void APP_MSGC_decomp_MSGID_PWR_STATE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BATT_LEVEL_DATA( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BATT_LEVEL_DATA, p0);
}

static inline void APP_MSGC_decomp_MSGID_BATT_LEVEL_DATA( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BATT_LEVEL_FORCED( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BATT_LEVEL_FORCED, p0);
}

static inline void APP_MSGC_decomp_MSGID_BATT_LEVEL_FORCED( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_CTRL_STATE_FORCED( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_CTRL_STATE_FORCED, p0);
}

static inline void APP_MSGC_decomp_MSGID_CTRL_STATE_FORCED( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_CTRL_STATE_REQ( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_CTRL_STATE_REQ, p0);
}

static inline void APP_MSGC_decomp_MSGID_CTRL_STATE_REQ( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_DEBUG_SET( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_DEBUG_SET, p0);
}

static inline void APP_MSGC_decomp_MSGID_DEBUG_SET( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_SET_IMM_ALERT( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_SET_IMM_ALERT, p0);
}

static inline void APP_MSGC_decomp_MSGID_SET_IMM_ALERT( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_GET_CH( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_GET_CH, p0);
}

static inline void APP_MSGC_decomp_MSGID_GET_CH( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_SENDER_TEST( msgc_t *mc_ptr, const uint16_t p0, const uint16_t p1 ) {
APP_MSGC_comp_U16U16( mc_ptr, MSGID_SENDER_TEST, p0, p1);
}

static inline void APP_MSGC_decomp_MSGID_SENDER_TEST( msgc_t *mc_ptr, uint16_t *p0, uint16_t *p1 ) {
APP_MSGC_decomp_U16U16( mc_ptr, p0, p1);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_RESET_TEST( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_RESET_TEST, p0);
}

static inline void APP_MSGC_decomp_MSGID_RESET_TEST( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PING0( msgc_t *mc_ptr ) {
APP_MSGC_comp_NONE( mc_ptr, MSGID_PING0);
}

static inline void APP_MSGC_decomp_MSGID_PING0( msgc_t *mc_ptr ) {
APP_MSGC_decomp_NONE( mc_ptr);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PING1( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PING1, p0);
}

static inline void APP_MSGC_decomp_MSGID_PING1( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PONG1( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PONG1, p0);
}

static inline void APP_MSGC_decomp_MSGID_PONG1( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PONG2( msgc_t *mc_ptr, const uint16_t p0, const uint16_t p1 ) {
APP_MSGC_comp_U16U16( mc_ptr, MSGID_PONG2, p0, p1);
}

static inline void APP_MSGC_decomp_MSGID_PONG2( msgc_t *mc_ptr, uint16_t *p0, uint16_t *p1 ) {
APP_MSGC_decomp_U16U16( mc_ptr, p0, p1);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_TUNNEL( msgc_t *mc_ptr, const uint8_t *arr, const uint8_t len ) {
APP_MSGC_comp_U8ARR14( mc_ptr, MSGID_TUNNEL, arr, len);
}

static inline void APP_MSGC_decomp_MSGID_TUNNEL( msgc_t *mc_ptr, uint8_t **arr, uint8_t *len ) {
APP_MSGC_decomp_U8ARR14( mc_ptr, arr, len);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BT_ON_RDY( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BT_ON_RDY, p0);
}

static inline void APP_MSGC_decomp_MSGID_BT_ON_RDY( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BT_ADVERTISE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BT_ADVERTISE, p0);
}

static inline void APP_MSGC_decomp_MSGID_BT_ADVERTISE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PRESSURE_DATA( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PRESSURE_DATA, p0);
}

static inline void APP_MSGC_decomp_MSGID_PRESSURE_DATA( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PRESSURE_TEMP( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PRESSURE_TEMP, p0);
}

static inline void APP_MSGC_decomp_MSGID_PRESSURE_TEMP( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PRESSURE_PHASE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PRESSURE_PHASE, p0);
}

static inline void APP_MSGC_decomp_MSGID_PRESSURE_PHASE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PRESSURE_CHECK( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PRESSURE_CHECK, p0);
}

static inline void APP_MSGC_decomp_MSGID_PRESSURE_CHECK( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PB_FRAME_CHECKH( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PB_FRAME_CHECKH, p0);
}

static inline void APP_MSGC_decomp_MSGID_PB_FRAME_CHECKH( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PB_FRAME_CHECKL( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PB_FRAME_CHECKL, p0);
}

static inline void APP_MSGC_decomp_MSGID_PB_FRAME_CHECKL( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PB_FRAME_PHASE( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PB_FRAME_PHASE, p0);
}

static inline void APP_MSGC_decomp_MSGID_PB_FRAME_PHASE( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PUT_CH( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_PUT_CH, p0);
}

static inline void APP_MSGC_decomp_MSGID_PUT_CH( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_ADT_TEMP_DATA( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_ADT_TEMP_DATA, p0);
}

static inline void APP_MSGC_decomp_MSGID_ADT_TEMP_DATA( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_ADT_TEMP_CHECK( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_ADT_TEMP_CHECK, p0);
}

static inline void APP_MSGC_decomp_MSGID_ADT_TEMP_CHECK( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_ADT_TEMP_INTERVAL( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_ADT_TEMP_INTERVAL, p0);
}

static inline void APP_MSGC_decomp_MSGID_ADT_TEMP_INTERVAL( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_BT_TUNNELMSG( msgc_t *mc_ptr, const uint16_t p0 ) {
APP_MSGC_comp_U16( mc_ptr, MSGID_BT_TUNNELMSG, p0);
}

static inline void APP_MSGC_decomp_MSGID_BT_TUNNELMSG( msgc_t *mc_ptr, uint16_t *p0 ) {
APP_MSGC_decomp_U16( mc_ptr, p0);
}


/*********************************************************************/

static inline void APP_MSGC_comp_MSGID_PING2( msgc_t *mc_ptr, const uint16_t p0, const uint16_t p1 ) {
APP_MSGC_comp_U16U16( mc_ptr, MSGID_PING2, p0, p1);
}

static inline void APP_MSGC_decomp_MSGID_PING2( msgc_t *mc_ptr, uint16_t *p0, uint16_t *p1 ) {
APP_MSGC_decomp_U16U16( mc_ptr, p0, p1);
}


/*********************************************************************/

#endif
// END OF FILE
