/* Generated By:JavaCC: Do not edit this line. RcdScriptParserConstants.java */
package org.thingml.rcd_scripter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RcdScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int CR_TAB = 11;
  /** RegularExpression Id. */
  int CR_TAB_JOIN = 12;
  /** RegularExpression Id. */
  int CR_COL = 13;
  /** RegularExpression Id. */
  int CR_ROW = 14;
  /** RegularExpression Id. */
  int ID_LITERAL = 15;
  /** RegularExpression Id. */
  int DEC_LITERAL = 16;
  /** RegularExpression Id. */
  int HEX_LITERAL = 17;
  /** RegularExpression Id. */
  int STRING_LITERAL = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int HEX_DIGIT = 21;
  /** RegularExpression Id. */
  int OBRA = 22;
  /** RegularExpression Id. */
  int CBRA = 23;
  /** RegularExpression Id. */
  int OCBRA = 24;
  /** RegularExpression Id. */
  int CCBRA = 25;
  /** RegularExpression Id. */
  int COMMA = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"/\"",
    "\"##\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 10>",
    "\"CREATE_TAB\"",
    "\"CREATE_TAB_JOIN\"",
    "\"CREATE_COL\"",
    "\"CREATE_ROW\"",
    "<ID_LITERAL>",
    "<DEC_LITERAL>",
    "<HEX_LITERAL>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<HEX_DIGIT>",
    "<OBRA>",
    "<CBRA>",
    "<OCBRA>",
    "<CCBRA>",
    "\",\"",
  };

}
