/* Generated By:JavaCC: Do not edit this line. RcdScript2ParserConstants.java */
package org.thingml.rcd_scripter2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RcdScript2ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int ADD = 11;
  /** RegularExpression Id. */
  int CELL = 12;
  /** RegularExpression Id. */
  int FILE = 13;
  /** RegularExpression Id. */
  int FOR_EACH = 14;
  /** RegularExpression Id. */
  int HAS = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int ROW = 20;
  /** RegularExpression Id. */
  int SETDEF = 21;
  /** RegularExpression Id. */
  int TABLE = 22;
  /** RegularExpression Id. */
  int VALUE = 23;
  /** RegularExpression Id. */
  int VAR_LITERAL = 24;
  /** RegularExpression Id. */
  int ID_LITERAL = 25;
  /** RegularExpression Id. */
  int DEC_LITERAL = 26;
  /** RegularExpression Id. */
  int HEX_LITERAL = 27;
  /** RegularExpression Id. */
  int STRING_LITERAL = 28;
  /** RegularExpression Id. */
  int LETTER = 29;
  /** RegularExpression Id. */
  int DIGIT = 30;
  /** RegularExpression Id. */
  int HEX_DIGIT = 31;
  /** RegularExpression Id. */
  int OBRA = 32;
  /** RegularExpression Id. */
  int CBRA = 33;
  /** RegularExpression Id. */
  int OCBRA = 34;
  /** RegularExpression Id. */
  int CCBRA = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int PERIOD = 37;
  /** RegularExpression Id. */
  int ASSIGN = 38;
  /** RegularExpression Id. */
  int DOLLAR = 39;
  /** RegularExpression Id. */
  int PLUS = 40;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"/\"",
    "\"##\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 10>",
    "\"ADD\"",
    "\"CELL\"",
    "\"FILE\"",
    "\"FOR_EACH\"",
    "\"HAS\"",
    "\"IF\"",
    "\"IN\"",
    "\"INT\"",
    "\"PRINT\"",
    "\"ROW\"",
    "\"SETDEF\"",
    "\"TABLE\"",
    "\"VALUE\"",
    "<VAR_LITERAL>",
    "<ID_LITERAL>",
    "<DEC_LITERAL>",
    "<HEX_LITERAL>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<HEX_DIGIT>",
    "<OBRA>",
    "<CBRA>",
    "<OCBRA>",
    "<CCBRA>",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"$\"",
    "\"+\"",
  };

}
