/* Generated By:JavaCC: Do not edit this line. RcdScript3ParserTreeConstants.java Version 6.1_2 */
package org.thingml.rcd_scripter3.parser;

public interface RcdScript3ParserTreeConstants
{
  public int JJTRCDSTART = 0;
  public int JJTVOID = 1;
  public int JJTRCDDEFHASHLIST = 2;
  public int JJTRCDDEFHASH = 3;
  public int JJTRCDDEFVARARRAY = 4;
  public int JJTRCDDEFFILE = 5;
  public int JJTRCDIFBLOCK = 6;
  public int JJTRCDFOREACHBLOCK = 7;
  public int JJTRCDTRUESCRIPT = 8;
  public int JJTRCDFALSESCRIPT = 9;
  public int JJTRCDPRINT = 10;
  public int JJTRCDOPEXPR = 11;
  public int JJTRCDVAR = 12;
  public int JJTRCDID = 13;
  public int JJTRCDSTRING = 14;
  public int JJTRCDINTNUM = 15;
  public int JJTRCDFLOATNUM = 16;
  public int JJTRCDHASH = 17;
  public int JJTRCDTUPL = 18;


  public String[] jjtNodeName = {
    "RcdStart",
    "void",
    "RcdDefHashList",
    "RcdDefHash",
    "RcdDefVarArray",
    "RcdDefFile",
    "RcdIfBlock",
    "RcdForEachBlock",
    "RcdTrueScript",
    "RcdFalseScript",
    "RcdPrint",
    "RcdOpExpr",
    "RcdVar",
    "RcdId",
    "RcdString",
    "RcdIntNum",
    "RcdFloatNum",
    "RcdHash",
    "RcdTupl",
  };
}
/* JavaCC - OriginalChecksum=318e7cace4ca8aecc88848148c99ab46 (do not edit this line) */
