/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.thingml.jjtree_ex3;

public
class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Eg3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f19b58fd7e9af4c5d17235492425a47e (do not edit this line) */
