/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.thingml.jjtree_ex3;

public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Eg3 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92034db6b407d6682de937d627f48d41 (do not edit this line) */
