/* Generated By:JavaCC: Do not edit this line. Eg3TreeConstants.java Version 6.1_2 */
package org.thingml.jjtree_ex3;

public interface Eg3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=753dfbb40f7d0404fcb8cca2f3581d7b (do not edit this line) */
