/* RcdScript2Parser.java */
/* Generated By:JavaCC: Do not edit this line. RcdScript2Parser.java */
   package org.thingml.rcd_scripter2.parser;
   import org.thingml.rcd_scripter2.jobs.*;
   public class RcdScript2Parser implements RcdScript2ParserConstants {
         public JobList_Obj makeJobs()throws ParseException, TokenMgrError
   { return(init()) ; }

  final public JobList_Obj init() throws ParseException {JobList_Obj jobList = new JobList_Obj("Main");
    Script(jobList);
    jj_consume_token(0);
{if ("" != null) return jobList;}
    throw new Error("Missing return statement in function");
  }

  final public void Script(JobList_Obj jobList) throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEF:
      case FOR_EACH:
      case IF:
      case IF_ROW:
      case PRINT:
      case VAR_LITERAL:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEF:{
        Def(jobList);
        break;
        }
      case PRINT:
      case VAR_LITERAL:{
        Statement(jobList);
        break;
        }
      case FOR_EACH:
      case IF:
      case IF_ROW:{
        Block(jobList);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }

  }

  final public void Def(JobList_Obj jobList) throws ParseException {Token TId_defVarName;
    jj_consume_token(DEF);
    TId_defVarName = jj_consume_token(VAR_LITERAL);
    jj_consume_token(ASSIGN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ROWLIST:{
      DefRowList(jobList, TId_defVarName);
      break;
      }
    case ROW:{
      DefRow(jobList, TId_defVarName);
      break;
      }
    case CELL:{
      DefCell(jobList, TId_defVarName);
      break;
      }
    case VARARRAY:{
      DefVarArray(jobList, TId_defVarName);
      break;
      }
    case FILE:{
      DefFile(jobList, TId_defVarName);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(SEMI);

  }

  final public void DefRowList(JobList_Obj jobList, Token TId_defVarName) throws ParseException {Token TId_tabInitName;
    String tabInitName = null;
    jj_consume_token(ROWLIST);
    jj_consume_token(OBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      TId_tabInitName = jj_consume_token(VAR_LITERAL);
tabInitName = TId_tabInitName.image;
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(CBRA);
jobList.addJob( new JobDefRowList(TId_defVarName, TId_defVarName.image, tabInitName));
  }

  final public void DefRow(JobList_Obj jobList, Token TId_defVarName) throws ParseException {Token TId_copyFromRowName = null;
    String copyFromRowName = null;
    JobList_VarCell jobCellList = null;
    jj_consume_token(ROW);
    jj_consume_token(OBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:
    case OCBRA:
    case ASSIGN:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VAR_LITERAL:
      case OCBRA:{
        jobCellList = CellList();
        break;
        }
      case ASSIGN:{
        jj_consume_token(ASSIGN);
        TId_copyFromRowName = jj_consume_token(VAR_LITERAL);
copyFromRowName = TId_copyFromRowName.image;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(CBRA);
jobList.addJob( new JobDefRow(TId_defVarName, TId_defVarName.image, copyFromRowName, jobCellList));
  }

  final public void DefCell(JobList_Obj jobList, Token TId_defVarName) throws ParseException {Token TId_copyFromCellName = null;
    String copyFromCellName = null;
    JobBase_VarCell jobCell = null;
    JobList_VarCell jobCellList = null;
    jj_consume_token(CELL);
    jj_consume_token(OBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:
    case OCBRA:{
      jobCell = CellEntry();
jobCellList = new JobList_VarCell("DefCell");
                jobCellList.addJob(jobCell);
      break;
      }
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      TId_copyFromCellName = jj_consume_token(VAR_LITERAL);
copyFromCellName = TId_copyFromCellName.image;
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(CBRA);
jobList.addJob( new JobDefCell(TId_defVarName, TId_defVarName.image, copyFromCellName, jobCellList));
  }

//void DefValue(JobList_Obj jobList, Token TId_defVarName):
//{
//    Token TId_copyFromValueName = null;
//    String copyFromValueName = null;
//    JobList_VarValueBase jobValue = null;
//}
//{
//    <VALUE>
//    <OBRA>
//    (
//        jobValue = Expr()
//        |
//        (
//            <ASSIGN>
//            TId_copyFromValueName = <VAR_LITERAL>
//            {copyFromValueName = TId_copyFromValueName.image;}
//        )
//    )
//    <CBRA>
//    {jobList.addJob( new JobDefValue(TId_defVarName, TId_defVarName.image, copyFromValueName, jobValue));}
//}
  final public 


void DefVarArray(JobList_Obj jobList, Token TId_defVarName) throws ParseException {Token TId_copyFromArrName = null;
    String copyFromArrName = null;
    JobList_VarValueBase valueJobListSize = null;
    JobList_VarValueBase valueJobListDefault = null;
    jj_consume_token(VARARRAY);
    jj_consume_token(OBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEC_LITERAL:
    case HEX_LITERAL:{
      valueJobListSize = ValueInt();
      jj_consume_token(COMMA);
      valueJobListDefault = Expr();
      break;
      }
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      TId_copyFromArrName = jj_consume_token(VAR_LITERAL);
copyFromArrName = TId_copyFromArrName.image;
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(CBRA);
jobList.addJob( new JobDefVarArray(TId_defVarName, TId_defVarName.image, copyFromArrName, valueJobListSize, valueJobListDefault));
  }

  final public void DefFile(JobList_Obj jobList, Token TId_defVarName) throws ParseException {JobList_VarValueBase retValueJobList;
    jj_consume_token(FILE);
    jj_consume_token(OBRA);
    retValueJobList = TxtExpr();
    jj_consume_token(CBRA);
jobList.addJob( new JobDefFile(TId_defVarName, TId_defVarName.image, retValueJobList));
  }

  final public void Statement(JobList_Obj jobList) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:{
      VarMethodOrAssign(jobList);
      break;
      }
    case PRINT:{
      Print(jobList);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(SEMI);

  }

  final public void VarMethodOrAssign(JobList_Obj jobList) throws ParseException {Token TId_varName;
    TId_varName = jj_consume_token(VAR_LITERAL);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PERIOD:{
      jj_consume_token(PERIOD);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SETDEF:{
        M_SetDefault(jobList, TId_varName);
        break;
        }
      case ADD:{
        M_Add(jobList, TId_varName);
        break;
        }
      case CLOSE:{
        M_Close(jobList, TId_varName);
        break;
        }
      case PRINT:{
        M_Print(jobList, TId_varName);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case OABRA:
    case ASSIGN:{
      VarNameAssign(jobList, TId_varName);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void M_SetDefault(JobList_Obj jobList, Token TId_varName) throws ParseException {Token TId_copyVarName = null;
    String copyVarName = null;
    JobList_VarCell jobCellList = null;
    jj_consume_token(SETDEF);
    jj_consume_token(OBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:
    case OCBRA:{
      jobCellList = CellList();
      break;
      }
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      TId_copyVarName = jj_consume_token(VAR_LITERAL);
copyVarName = TId_copyVarName.image;
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(CBRA);
jobList.addJob( new JobVarSetDefault(TId_varName, TId_varName.image, copyVarName, jobCellList));
  }

  final public void M_Add(JobList_Obj jobList, Token TId_varName) throws ParseException {Token TId_copyVarName = null;
    String copyVarName = null;
    JobList_VarCell jobCellList = null;
    jj_consume_token(ADD);
    jj_consume_token(OBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:
    case OCBRA:{
      jobCellList = CellList();
      break;
      }
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      TId_copyVarName = jj_consume_token(VAR_LITERAL);
copyVarName = TId_copyVarName.image;
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(CBRA);
jobList.addJob( new JobVarAddCellList(TId_varName, TId_varName.image, copyVarName, jobCellList));
  }

  final public void M_Close(JobList_Obj jobList, Token TId_varName) throws ParseException {
    jj_consume_token(CLOSE);
    jj_consume_token(OBRA);
    jj_consume_token(CBRA);
jobList.addJob( new JobVarClose(TId_varName, TId_varName.image));
  }

  final public void M_Print(JobList_Obj jobList, Token TId_varName) throws ParseException {JobList_VarValueBase retValueJobList;
    jj_consume_token(PRINT);
    jj_consume_token(OBRA);
    retValueJobList = TxtExpr();
    jj_consume_token(CBRA);
jobList.addJob( new JobPrint(TId_varName, TId_varName.image, retValueJobList));
  }

  final public void VarNameAssign(JobList_Obj jobList, Token TId_varName) throws ParseException {JobList_VarValueBase indexValueJobList = null;
    JobList_VarValueBase valueJobList = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OABRA:{
      jj_consume_token(OABRA);
      indexValueJobList = NumExpr();
      jj_consume_token(CABRA);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(ASSIGN);
    valueJobList = Expr();
jobList.addJob( new JobVarNameAssign(TId_varName, TId_varName.image, indexValueJobList, valueJobList));
  }

  final public void Print(JobList_Obj jobList) throws ParseException {JobList_VarValueBase retValueJobList;
    String fileName = null;
    Token TId;
    TId = jj_consume_token(PRINT);
    jj_consume_token(OBRA);
    retValueJobList = TxtExpr();
    jj_consume_token(CBRA);
jobList.addJob( new JobPrint(TId, fileName, retValueJobList));
  }

  final public void Block(JobList_Obj jobList) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FOR_EACH:{
      ForEach(jobList);
      break;
      }
    case IF_ROW:{
      IfRow(jobList);
      break;
      }
    case IF:{
      IfVar(jobList);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void ForEach(JobList_Obj jobList) throws ParseException {JobList_Obj forEachJobList = new JobList_Obj("ForEachScript");
    Token TId_loopVar;
    Token TId_inVar;
    jj_consume_token(FOR_EACH);
    jj_consume_token(OBRA);
    TId_loopVar = jj_consume_token(VAR_LITERAL);
    jj_consume_token(IN);
    TId_inVar = jj_consume_token(VAR_LITERAL);
    jj_consume_token(CBRA);
    jj_consume_token(OCBRA);
    Script(forEachJobList);
    jj_consume_token(CCBRA);
jobList.addJob( new JobForEach(TId_loopVar, TId_loopVar.image, TId_inVar.image, forEachJobList));
  }

  final public void IfRow(JobList_Obj jobList) throws ParseException {JobList_Obj ifJobList = new JobList_Obj("IfRowScript");
    JobList_Obj elseJobList = new JobList_Obj("ElseRowScript");
    Token TId_rowVar;
    JobBase_VarCell jobCell;
    JobList_VarCell jobCellList = null;
    jj_consume_token(IF_ROW);
    jj_consume_token(OBRA);
    TId_rowVar = jj_consume_token(VAR_LITERAL);
    jj_consume_token(HAS);
    jobCell = CellEntry();
    jj_consume_token(CBRA);
    jj_consume_token(OCBRA);
    Script(ifJobList);
    jj_consume_token(CCBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(OCBRA);
      Script(elseJobList);
      jj_consume_token(CCBRA);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
jobCellList = new JobList_VarCell("IfRowCell");
        jobCellList.addJob(jobCell);
        jobList.addJob( new JobIfRow(TId_rowVar, TId_rowVar.image, jobCellList, ifJobList, elseJobList));
  }

  final public void IfVar(JobList_Obj jobList) throws ParseException {JobList_Obj ifJobList = new JobList_Obj("IfVarScript");
    JobList_Obj elseJobList = new JobList_Obj("ElseVarScript");
    Token TId;
    JobList_VarValueBase leftValueJobList;
    JobList_VarValueBase rightValueJobList;
    TId = jj_consume_token(IF);
    jj_consume_token(OBRA);
    leftValueJobList = Expr();
    jj_consume_token(EQUAL);
    rightValueJobList = Expr();
    jj_consume_token(CBRA);
    jj_consume_token(OCBRA);
    Script(ifJobList);
    jj_consume_token(CCBRA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(OCBRA);
      Script(elseJobList);
      jj_consume_token(CCBRA);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
jobList.addJob( new JobIfVarEq(TId, leftValueJobList, rightValueJobList, ifJobList, elseJobList));
  }

  final public JobList_VarCell CellList() throws ParseException {JobBase_VarCell cellJob = null;
    JobList_VarCell jobList = new JobList_VarCell("CellList");
    cellJob = CellEntry();
jobList.addJob(cellJob);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      cellJob = CellEntry();
jobList.addJob(cellJob);
    }
{if ("" != null) return jobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobBase_VarCell CellEntry() throws ParseException {JobBase_VarCell cellJob;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:{
      cellJob = CellVar_VarId();
      break;
      }
    case OCBRA:{
      cellJob = CellTupl();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return cellJob;}
    throw new Error("Missing return statement in function");
  }

  final public JobBase_VarCell CellVar_VarId() throws ParseException {JobBase_VarCell cellJob;
    Token   TId_var;
    Token   TId_id = null;
    TId_var = jj_consume_token(VAR_LITERAL);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PERIOD:{
      jj_consume_token(PERIOD);
      //            <CELL>
      //            <OBRA>
                  TId_id = jj_consume_token(ID_LITERAL);
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
if (TId_id != null) {
            cellJob = new JobCreateCellVarId(TId_var, TId_var.image, TId_id.image);
        } else {
            cellJob = new JobCreateCellVar(TId_var, TId_var.image);
        }
        {if ("" != null) return cellJob;}
    throw new Error("Missing return statement in function");
  }

  final public JobBase_VarCell CellTupl() throws ParseException {JobBase_VarCell cellJob;
    JobList_VarValueBase valueJobList;
    Token   TId;
    jj_consume_token(OCBRA);
    TId = jj_consume_token(ID_LITERAL);
    jj_consume_token(COMMA);
    valueJobList = Expr();
    jj_consume_token(CCBRA);
cellJob = new JobCreateCell(TId, TId.image, valueJobList);
        {if ("" != null) return cellJob;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase Expr() throws ParseException {JobList_VarValueBase retValueJobList;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:
    case DEC_LITERAL:
    case HEX_LITERAL:{
      retValueJobList = NumExpr();
      break;
      }
    case ID_LITERAL:
    case STRING_LITERAL:{
      retValueJobList = TxtExpr();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase NumExpr() throws ParseException {JobList_VarValueBase valueJobList1;
    JobList_VarValueBase valueJobList2;
    JobList_VarValueBase retValueJobList;
    Token   TId;
    retValueJobList = Term();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        TId = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        TId = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      valueJobList2 = Term();
valueJobList1 = retValueJobList;
                retValueJobList = new JobList_VarValueBase("PLUS/MINUS");
                retValueJobList.addJob( new JobCreateValueOperation(TId, TId.image, valueJobList1, valueJobList2));
    }
{if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase Term() throws ParseException {JobList_VarValueBase valueJobList1;
    JobList_VarValueBase valueJobList2;
    JobList_VarValueBase retValueJobList;
    Token   TId;
    retValueJobList = Factor();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MUL:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MUL:{
        TId = jj_consume_token(MUL);
        break;
        }
      case DIV:{
        TId = jj_consume_token(DIV);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      valueJobList2 = Factor();
valueJobList1 = retValueJobList;
                retValueJobList = new JobList_VarValueBase("MULDIV");
                retValueJobList.addJob( new JobCreateValueOperation(TId, TId.image, valueJobList1, valueJobList2));
    }
{if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase Factor() throws ParseException {JobList_VarValueBase retValueJobList;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR_LITERAL:{
      retValueJobList = ValueVar_VarId_VarIndex();
      break;
      }
    case DEC_LITERAL:
    case HEX_LITERAL:{
      retValueJobList = ValueInt();
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase ValueVar_VarId_VarIndex() throws ParseException {JobList_VarValueBase retValueJobList;
    JobBase_VarValueBase valueJob;
    Token   TId_var;
    Token   TId_id = null;
    JobList_VarValueBase indexValueJobList = null;
    TId_var = jj_consume_token(VAR_LITERAL);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OABRA:
    case PERIOD:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PERIOD:{
        jj_consume_token(PERIOD);
        TId_id = jj_consume_token(ID_LITERAL);
        break;
        }
      case OABRA:{
        jj_consume_token(OABRA);
        indexValueJobList = NumExpr();
        jj_consume_token(CABRA);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      ;
    }
if (TId_id != null) {
            valueJob = new JobCreateValueVarId(TId_var, TId_var.image, TId_id.image);
        } else if (indexValueJobList != null) {
            valueJob = new JobCreateValueVarIndex(TId_var, TId_var.image, indexValueJobList);
        } else {
            valueJob = new JobCreateValueVar(TId_var, TId_var.image);
        }
        retValueJobList = new JobList_VarValueBase("ValueVar_VarId");
        retValueJobList.addJob( valueJob );
        {if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase ValueInt() throws ParseException {JobList_VarValueBase retValueJobList;
    JobBase_VarValueBase valueJob;
    Token   TId;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEC_LITERAL:{
      TId = jj_consume_token(DEC_LITERAL);
      break;
      }
    case HEX_LITERAL:{
      TId = jj_consume_token(HEX_LITERAL);
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
valueJob = new JobCreateValueInt(TId, TId.image);
        retValueJobList = new JobList_VarValueBase("ValueInt");
        retValueJobList.addJob( valueJob );
        {if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase TxtExpr() throws ParseException {JobList_VarValueBase valueJobList1;
    JobList_VarValueBase valueJobList2;
    JobList_VarValueBase retValueJobList;
    Token   TId;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL:{
      retValueJobList = ValueString();
      break;
      }
    case ID_LITERAL:{
      retValueJobList = ValueId();
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_5;
      }
      TId = jj_consume_token(PLUS);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STRING_LITERAL:{
        valueJobList2 = ValueString();
        break;
        }
      case ID_LITERAL:{
        valueJobList2 = ValueId();
        break;
        }
      case DEC_LITERAL:
      case HEX_LITERAL:{
        valueJobList2 = ValueInt();
        break;
        }
      case VAR_LITERAL:{
        valueJobList2 = ValueVar_VarId_VarIndex();
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
valueJobList1 = retValueJobList;
                retValueJobList = new JobList_VarValueBase("SPLUS");
                retValueJobList.addJob( new JobCreateValueOperation(TId, "S+", valueJobList1, valueJobList2));
    }
{if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase ValueId() throws ParseException {JobList_VarValueBase retValueJobList;
    JobBase_VarValueBase valueJob;
    Token   TId;
    TId = jj_consume_token(ID_LITERAL);
valueJob = new JobCreateValueString(TId, TId.image, false);
        retValueJobList = new JobList_VarValueBase("ValueId");
        retValueJobList.addJob( valueJob );
        {if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  final public JobList_VarValueBase ValueString() throws ParseException {JobList_VarValueBase retValueJobList;
    JobBase_VarValueBase valueJob;
    Token   TId;
    TId = jj_consume_token(STRING_LITERAL);
valueJob = new JobCreateValueString(TId, TId.image, true);
        retValueJobList = new JobList_VarValueBase("ValueString");
        retValueJobList.addJob( valueJob );
        {if ("" != null) return retValueJobList;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public RcdScript2ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[32];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x111a0800,0x111a0800,0xa00e000,0x0,0x10000000,0x10000000,0x10000000,0xc0000000,0x11000000,0x5011000,0x0,0x10000000,0x10000000,0x0,0x1a0000,0x200000,0x200000,0x0,0x10000000,0x0,0xf0000000,0x0,0x0,0x0,0x0,0xd0000000,0x0,0x0,0xc0000000,0x20000000,0x0,0xf0000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x2000,0x2040,0x2040,0x2040,0x2000,0x0,0x0,0x2900,0x2040,0x2040,0x100,0x0,0x0,0x0,0x400,0x40,0x800,0x1,0x30000,0x30000,0xc0000,0xc0000,0x0,0x900,0x900,0x0,0x1,0x10000,0x1,};
   }

  /** Constructor with InputStream. */
  public RcdScript2Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public RcdScript2Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RcdScript2ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public RcdScript2Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RcdScript2ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
      jj_input_stream = new SimpleCharStream(stream, 1, 1);
   } else {
      jj_input_stream.ReInit(stream, 1, 1);
   }
   if (token_source == null) {
      token_source = new RcdScript2ParserTokenManager(jj_input_stream);
   }

    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public RcdScript2Parser(RcdScript2ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RcdScript2ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 32; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 32; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

   }
