/* Generated By:JavaCC: Do not edit this line. RcdScript2ParserConstants.java */
package org.thingml.rcd_scripter2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RcdScript2ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int DEF = 13;
  /** RegularExpression Id. */
  int ADD = 14;
  /** RegularExpression Id. */
  int VARARRAY = 15;
  /** RegularExpression Id. */
  int CELL = 16;
  /** RegularExpression Id. */
  int FILE = 17;
  /** RegularExpression Id. */
  int CLOSE = 18;
  /** RegularExpression Id. */
  int FOR_EACH = 19;
  /** RegularExpression Id. */
  int HAS = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int IF_ROW = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int IN = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int PRINT = 26;
  /** RegularExpression Id. */
  int PRINTLN = 27;
  /** RegularExpression Id. */
  int ROW = 28;
  /** RegularExpression Id. */
  int SETDEF = 29;
  /** RegularExpression Id. */
  int ROWLIST = 30;
  /** RegularExpression Id. */
  int VAR_LITERAL = 31;
  /** RegularExpression Id. */
  int ID_LITERAL = 32;
  /** RegularExpression Id. */
  int DEC_LITERAL = 33;
  /** RegularExpression Id. */
  int HEX_LITERAL = 34;
  /** RegularExpression Id. */
  int STRING_LITERAL = 35;
  /** RegularExpression Id. */
  int LETTER = 36;
  /** RegularExpression Id. */
  int DIGIT = 37;
  /** RegularExpression Id. */
  int HEX_DIGIT = 38;
  /** RegularExpression Id. */
  int OBRA = 39;
  /** RegularExpression Id. */
  int CBRA = 40;
  /** RegularExpression Id. */
  int OCBRA = 41;
  /** RegularExpression Id. */
  int CCBRA = 42;
  /** RegularExpression Id. */
  int OABRA = 43;
  /** RegularExpression Id. */
  int CABRA = 44;
  /** RegularExpression Id. */
  int COMMA = 45;
  /** RegularExpression Id. */
  int PERIOD = 46;
  /** RegularExpression Id. */
  int SEMI = 47;
  /** RegularExpression Id. */
  int ASSIGN = 48;
  /** RegularExpression Id. */
  int EQUAL = 49;
  /** RegularExpression Id. */
  int DOLLAR = 50;
  /** RegularExpression Id. */
  int PLUS = 51;
  /** RegularExpression Id. */
  int MINUS = 52;
  /** RegularExpression Id. */
  int MUL = 53;
  /** RegularExpression Id. */
  int DIV = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "\"//\"",
    "\"*/\"",
    "\"/*\"",
    "\"##\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 12>",
    "\"DEF\"",
    "\"ADD\"",
    "\"VARARRAY\"",
    "\"CELL\"",
    "\"FILE\"",
    "\"CLOSE\"",
    "\"FOR_EACH\"",
    "\"HAS\"",
    "\"IF\"",
    "\"IF_ROW\"",
    "\"ELSE\"",
    "\"IN\"",
    "\"INT\"",
    "\"PRINT\"",
    "\"PRINTLN\"",
    "\"ROW\"",
    "\"SETDEF\"",
    "\"ROWLIST\"",
    "<VAR_LITERAL>",
    "<ID_LITERAL>",
    "<DEC_LITERAL>",
    "<HEX_LITERAL>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<HEX_DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"=\"",
    "\"==\"",
    "\"$\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
